Repository imvmanish19/RealTimeChatApp, pull requests merged in 2020-10, with the labels that each got.

#1 Added a div to the webpage
  public/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#2 Centered the login box
  public/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#3 Changed Background color
  public/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#4 Create CONTRIBUTION.md
  CONTRIBUTION.md
Labels: documentation

#6 Added Message Recieved Feature
  public/rooms.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7 feat: redesign layout
  public/assets/SelfieDoodle.png
  public/assets/SleekDoodle.png
  public/index.html
  public/rooms.js
  public/script.js
  public/style.css
  yarn.lock
Labels: hacktoberfest, hacktoberfest-accepted
